language: php

php:
  - 5.3

env:
  - DATABASE=sqlite
  - DATABASE=mysql

before_script:
  - ./tests/travis_${DATABASE}.sh

script: phpunit -c tests/phpunit_${DATABASE}.xml.dist

notifications:
    irc: "irc.freenode.org#midgard"
