language: php

php:
  - 5.3

env:
  - DATABASE=sqlite
  - DATABASE=mysql

before_script:
  - ./tests/travis_${DATABASE}.sh

script: ./tests/travis_test.sh

notifications:
    irc: "irc.freenode.org#midgard"
