language: php

php:
  - 5.4

env:
  - DATABASE=sqlite
  - DATABASE=mysql

before_script:
  - ./tests/travis_${DATABASE}.sh

script: php -v; valgrind -v --log-file=segfault.log phpunit -c api-test/phpunit_${DATABASE}.xml.dist; cat segfault.log

notifications:
    irc: "irc.freenode.org#midgard"
