language: php

php:
  - 5.3
  - 5.4

env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgresql
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=gjallarhorn

before_script:
  - ./tests/travis_${DATABASE}.sh

script: phpunit -c tests/phpunit_${DATABASE}.xml.dist 

notifications:
    irc: "irc.freenode.org#midgard"
